### ISSUE TITLE
Static content URL issue

### ISSUE THREAD

**Issue by hocally** [gopher-motorsports/trackside-ops#3]
The following line is causing issues when deployed behind gunicorn:
https://github.com/gopher-motorsports/trackside-ops/blob/b1f80e84a6bbceefad23113b5eb6ed82d6b889f7/data_entry/templates/data_entry/home.html#L8
Can it be switched to use a template static tag like so?
https://github.com/gopher-motorsports/trackside-ops/blob/b1f80e84a6bbceefad23113b5eb6ed82d6b889f7/data_entry/templates/data_entry/home.html#L14

**Comment by lealal** [comment]
Solved! Had to add STATICFILES_DIRS to settings.py
